In [71]:
import pandas as pd
import numpy as np

df = pd.DataFrame()

df['MANGERID'] = ['Sridhar','Rajkumar','Rajkumar','Monish','Ranga','Hathija','Rajkumar','Monish']
df['EMPID'] = ['Rajkumar','Monish','Jo','Hathija','Nish','Eniya','Ramya','Vijay']

final_df = pd.DataFrame(columns=['MANGERID','EMPID'])
level = 1
emp = ''
#for i in df['MANGERID']:
def fun(i,level):
    mask = np.column_stack([df[col].str.contains(i, na=False) for col in df])
    new_df = df.loc[mask.any(axis=1)]
    if len(new_df) == 1:
        return new_df['MANGERID'], level
    mang = ''.join(new_df[new_df['EMPID'] == i]['MANGERID'].values)
    level+=1
    return fun(mang,level)
    

def mngrEMP(i):
    mask = np.column_stack([df[col].str.contains(i, na=False) for col in df])
    new_df1 = df.loc[mask.any(axis=1)]
    new_df = df[df['MANGERID'] == i]
    if len(new_df) == 1:
        global final_df
        
        if len(new_df) > 1:
            for id in set(new_df[new_df['MANGERID'] == i]['EMPID'].values):
                d1 = {'MANGERID':manager,'EMPID':id,'Level':[1]}
                data = pd.DataFrame(d1)
                final_df = final_df.append(data,ignore_index=True)
        else:
            final_df = final_df.append(new_df,ignore_index=True)
    else:
        global emp
        new_df = df[df['MANGERID'] == i]
        mang = ''.join(df[df['EMPID'] == i]['MANGERID'].values)
        manager, level = fun(mang,1)
        if len(new_df[new_df['MANGERID'] == i]['EMPID'].values) == 1:
            emp = ''.join(new_df[new_df['MANGERID'] == i]['EMPID'].values)
        else:
            if len(new_df) > 1:
                for id in set(new_df[new_df['MANGERID'] == i]['EMPID'].values):
                    d1 = {'MANGERID':manager,'EMPID':id,'Level':[level+1]}
                    data = pd.DataFrame(d1)
                    final_df = final_df.append(data,ignore_index=True)
                           
        d = {'MANGERID':manager,
             'EMPID':emp,
             'Level':[level+1]}
        app_df = pd.DataFrame(d)
        final_df = final_df.append(app_df,ignore_index=True)
        
#(df['MANGERID']).apply(mngrEMP)
for i in set(df['MANGERID']):
    mngrEMP(i)
final_df

      EMPID  Level MANGERID
0     Eniya    NaN  Hathija
1     Vijay    3.0  Sridhar
2   Hathija    3.0  Sridhar
3              3.0  Sridhar
4    Monish    2.0  Sridhar
5        Jo    2.0  Sridhar
6     Ramya    2.0  Sridhar
7              2.0  Sridhar
8  Rajkumar    NaN  Sridhar
9      Nish    NaN    Ranga

In [76]:
import pandas as pd
import numpy as np

df = pd.DataFrame()

df['MANGERID'] = ['Sridhar','Rajkumar','Monish','Ranga','Hathija']
df['EMPID'] = ['Rajkumar','Monish','Hathija','Nish','Eniya']

final_df = pd.DataFrame(columns=['MANGERID','EMPID'])
level = 1
#for i in df['MANGERID']:
def fun(i,level):
    mask = np.column_stack([df[col].str.contains(i, na=False) for col in df])
    new_df = df.loc[mask.any(axis=1)]
    if len(new_df) == 1:
        return new_df['MANGERID'], level
    mang = ''.join(new_df[new_df['EMPID'] == i]['MANGERID'].values)
    level+=1
    return fun(mang,level)

    

def mngrEMP(i):
    mask = np.column_stack([df[col].str.contains(i, na=False) for col in df])
    new_df = df.loc[mask.any(axis=1)]
    if len(new_df) == 1:
        new_df['Level'] = 1
        global final_df
        final_df = final_df.append(new_df,ignore_index=True)
    else:
        new_df = df[df['MANGERID'] == i]
        mang = ''.join(df[df['EMPID'] == i]['MANGERID'].values)
        
        emp = ''.join(new_df[new_df['MANGERID'] == i]['EMPID'].values)
        manager, level = fun(mang,1)
        d = {'MANGERID':manager,
             'EMPID':emp,
             'Level':[level+1]}
        app_df = pd.DataFrame(d)
        final_df = final_df.append(app_df,ignore_index=True)
        
df['MANGERID'].apply(mngrEMP)
final_df

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\pandas\core\frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

      EMPID  Level MANGERID
0  Rajkumar    1.0  Sridhar
1    Monish    2.0  Sridhar
2   Hathija    3.0  Sridhar
3      Nish    1.0    Ranga
4     Eniya    4.0  Sridhar